name: CI/CD Docker

on:
  push:
    branches:
      - '**'       # toutes les branches
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  lint-build:
    runs-on: ubuntu-latest
    outputs:
      owner_lower: ${{ steps.prep.outputs.owner_lower }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binary
        run: go build -o mclog2event .

  docker-push:
    needs: lint-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner name
        id: prep
        run: echo "owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ needs.lint-build.outputs.owner_lower }}/mclog2event:${{ github.sha }}
            ghcr.io/${{ needs.lint-build.outputs.owner_lower }}/mclog2event:latest
